# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

ifneq ($(VERBOSE),1)
VV=@
endif

MXX=/usr/sbin/gcc
MM=/usr/sbin/gcc
CC=/usr/sbin/gcc
AS=/usr/sbin/gcc
CXX=/usr/sbin/gcc

LD=/usr/sbin/g++
SH=/usr/sbin/g++
AR=/usr/sbin/ar


test_CXXFLAGS=-m64 -g -O0
test_CXXFLAGS=-m64 -g -O0
test_LDFLAGS=-m64 -lyaml-cpp

default:  test

all:  test

.PHONY: default all  test

test: build/linux/x86_64/debug/test
build/linux/x86_64/debug/test: build/.objs/test/linux/x86_64/debug/tests/test_iomanager.cpp.o build/.objs/test/linux/x86_64/debug/sylar/scheduler.cpp.o build/.objs/test/linux/x86_64/debug/sylar/thread.cpp.o build/.objs/test/linux/x86_64/debug/sylar/iomanager.cpp.o build/.objs/test/linux/x86_64/debug/sylar/util.cpp.o build/.objs/test/linux/x86_64/debug/sylar/config.cpp.o build/.objs/test/linux/x86_64/debug/sylar/log.cpp.o build/.objs/test/linux/x86_64/debug/sylar/fiber.cpp.o
	@echo linking.debug test
	@mkdir -p build/linux/x86_64/debug
	$(VV)$(LD) -o build/linux/x86_64/debug/test build/.objs/test/linux/x86_64/debug/tests/test_iomanager.cpp.o build/.objs/test/linux/x86_64/debug/sylar/scheduler.cpp.o build/.objs/test/linux/x86_64/debug/sylar/thread.cpp.o build/.objs/test/linux/x86_64/debug/sylar/iomanager.cpp.o build/.objs/test/linux/x86_64/debug/sylar/util.cpp.o build/.objs/test/linux/x86_64/debug/sylar/config.cpp.o build/.objs/test/linux/x86_64/debug/sylar/log.cpp.o build/.objs/test/linux/x86_64/debug/sylar/fiber.cpp.o $(test_LDFLAGS)

build/.objs/test/linux/x86_64/debug/tests/test_iomanager.cpp.o: tests/test_iomanager.cpp
	@echo compiling.debug tests/test_iomanager.cpp
	@mkdir -p build/.objs/test/linux/x86_64/debug/tests
	$(VV)$(CXX) -c $(test_CXXFLAGS) -o build/.objs/test/linux/x86_64/debug/tests/test_iomanager.cpp.o tests/test_iomanager.cpp

build/.objs/test/linux/x86_64/debug/sylar/scheduler.cpp.o: sylar/scheduler.cpp
	@echo compiling.debug sylar/scheduler.cpp
	@mkdir -p build/.objs/test/linux/x86_64/debug/sylar
	$(VV)$(CXX) -c $(test_CXXFLAGS) -o build/.objs/test/linux/x86_64/debug/sylar/scheduler.cpp.o sylar/scheduler.cpp

build/.objs/test/linux/x86_64/debug/sylar/thread.cpp.o: sylar/thread.cpp
	@echo compiling.debug sylar/thread.cpp
	@mkdir -p build/.objs/test/linux/x86_64/debug/sylar
	$(VV)$(CXX) -c $(test_CXXFLAGS) -o build/.objs/test/linux/x86_64/debug/sylar/thread.cpp.o sylar/thread.cpp

build/.objs/test/linux/x86_64/debug/sylar/iomanager.cpp.o: sylar/iomanager.cpp
	@echo compiling.debug sylar/iomanager.cpp
	@mkdir -p build/.objs/test/linux/x86_64/debug/sylar
	$(VV)$(CXX) -c $(test_CXXFLAGS) -o build/.objs/test/linux/x86_64/debug/sylar/iomanager.cpp.o sylar/iomanager.cpp

build/.objs/test/linux/x86_64/debug/sylar/util.cpp.o: sylar/util.cpp
	@echo compiling.debug sylar/util.cpp
	@mkdir -p build/.objs/test/linux/x86_64/debug/sylar
	$(VV)$(CXX) -c $(test_CXXFLAGS) -o build/.objs/test/linux/x86_64/debug/sylar/util.cpp.o sylar/util.cpp

build/.objs/test/linux/x86_64/debug/sylar/config.cpp.o: sylar/config.cpp
	@echo compiling.debug sylar/config.cpp
	@mkdir -p build/.objs/test/linux/x86_64/debug/sylar
	$(VV)$(CXX) -c $(test_CXXFLAGS) -o build/.objs/test/linux/x86_64/debug/sylar/config.cpp.o sylar/config.cpp

build/.objs/test/linux/x86_64/debug/sylar/log.cpp.o: sylar/log.cpp
	@echo compiling.debug sylar/log.cpp
	@mkdir -p build/.objs/test/linux/x86_64/debug/sylar
	$(VV)$(CXX) -c $(test_CXXFLAGS) -o build/.objs/test/linux/x86_64/debug/sylar/log.cpp.o sylar/log.cpp

build/.objs/test/linux/x86_64/debug/sylar/fiber.cpp.o: sylar/fiber.cpp
	@echo compiling.debug sylar/fiber.cpp
	@mkdir -p build/.objs/test/linux/x86_64/debug/sylar
	$(VV)$(CXX) -c $(test_CXXFLAGS) -o build/.objs/test/linux/x86_64/debug/sylar/fiber.cpp.o sylar/fiber.cpp

clean:  clean_test

clean_test: 
	@rm -rf build/linux/x86_64/debug/test
	@rm -rf build/linux/x86_64/debug/test.sym
	@rm -rf build/.objs/test/linux/x86_64/debug/tests/test_iomanager.cpp.o
	@rm -rf build/.objs/test/linux/x86_64/debug/sylar/scheduler.cpp.o
	@rm -rf build/.objs/test/linux/x86_64/debug/sylar/thread.cpp.o
	@rm -rf build/.objs/test/linux/x86_64/debug/sylar/iomanager.cpp.o
	@rm -rf build/.objs/test/linux/x86_64/debug/sylar/util.cpp.o
	@rm -rf build/.objs/test/linux/x86_64/debug/sylar/config.cpp.o
	@rm -rf build/.objs/test/linux/x86_64/debug/sylar/log.cpp.o
	@rm -rf build/.objs/test/linux/x86_64/debug/sylar/fiber.cpp.o

